from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 474)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 420, 731, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button.setObjectName("Button")
        self.verticalLayout.addWidget(self.Button)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Button1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button1.setObjectName("Button1")
        self.gridLayout.addWidget(self.Button1, 0, 0, 1, 1)
        self.Button2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button2.setObjectName("Button2")
        self.gridLayout.addWidget(self.Button2, 1, 0, 1, 1)
        self.Button6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button6.setObjectName("Button6")
        self.gridLayout.addWidget(self.Button6, 5, 0, 1, 1)
        self.Button3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button3.setObjectName("Button3")
        self.gridLayout.addWidget(self.Button3, 2, 0, 1, 1)
        self.Button5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button5.setObjectName("Button5")
        self.gridLayout.addWidget(self.Button5, 4, 0, 1, 1)
        self.Button8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button8.setObjectName("Button8")
        self.gridLayout.addWidget(self.Button8, 7, 0, 1, 1)
        self.Button7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button7.setObjectName("Button7")
        self.gridLayout.addWidget(self.Button7, 6, 0, 1, 1)
        self.Button4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Button4.setObjectName("Button4")
        self.gridLayout.addWidget(self.Button4, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(170, 0, 171, 421))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Button9 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button9.setObjectName("Button9")
        self.gridLayout_2.addWidget(self.Button9, 0, 0, 1, 1)
        self.Button11 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button11.setObjectName("Button11")
        self.gridLayout_2.addWidget(self.Button11, 2, 0, 1, 1)
        self.Button12 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button12.setObjectName("Button12")
        self.gridLayout_2.addWidget(self.Button12, 3, 0, 1, 1)
        self.Button10 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button10.setObjectName("Button10")
        self.gridLayout_2.addWidget(self.Button10, 1, 0, 1, 1)
        self.Button15 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button15.setObjectName("Button15")
        self.gridLayout_2.addWidget(self.Button15, 6, 0, 1, 1)
        self.Button14 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button14.setObjectName("Button14")
        self.gridLayout_2.addWidget(self.Button14, 5, 0, 1, 1)
        self.Button16 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button16.setObjectName("Button16")
        self.gridLayout_2.addWidget(self.Button16, 7, 0, 1, 1)
        self.Button13 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Button13.setProperty("1", 0)
        self.Button13.setObjectName("Button13")
        self.gridLayout_2.addWidget(self.Button13, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 361, 411))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button.setText(_translate("MainWindow", "Поехали"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button1.setProperty("CoordX", _translate("MainWindow", "6.55"))
        self.Button1.setProperty("CoordY", _translate("MainWindow", "-3.44"))
        self.Button1.setProperty("CoordW", _translate("MainWindow", "0.017"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button2.setProperty("CoordX", _translate("MainWindow", "6.66"))
        self.Button2.setProperty("CoordY", _translate("MainWindow", "-4.57"))
        self.Button2.setProperty("CoordW", _translate("MainWindow", "0.03"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button3.setProperty("CoordX", _translate("MainWindow", "6.65"))
        self.Button3.setProperty("CoordY", _translate("MainWindow", "-5.89"))
        self.Button3.setProperty("CoordW", _translate("MainWindow", "-0.03"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button4.setProperty("CoordX", _translate("MainWindow", "6.48"))
        self.Button4.setProperty("CoordY", _translate("MainWindow", "-7.31"))
        self.Button4.setProperty("CoordW", _translate("MainWindow", "-0.02"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Button5.setProperty("CoordX", _translate("MainWindow", "6.47"))
        self.Button5.setProperty("CoordY", _translate("MainWindow", "-8.61"))
        self.Button5.setProperty("CoordW", _translate("MainWindow", "-0.11"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button6.setProperty("CoordX", _translate("MainWindow", "6.37"))
        self.Button6.setProperty("CoordY", _translate("MainWindow", "-9.67"))
        self.Button6.setProperty("CoordW", _translate("MainWindow", "-0.106"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.Button7.setProperty("CoordX", _translate("MainWindow", "9.93"))
        self.Button7.setProperty("CoordY", _translate("MainWindow", "-3.29"))
        self.Button7.setProperty("CoordW", _translate("MainWindow", "-0.07"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.Button8.setProperty("CoordX", _translate("MainWindow", "10.02"))
        self.Button8.setProperty("CoordY", _translate("MainWindow", "-4.67"))
        self.Button8.setProperty("CoordW", _translate("MainWindow", "-0.06"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button9.setProperty("CoordX", _translate("MainWindow", "10.1"))
        self.Button9.setProperty("CoordY", _translate("MainWindow", "-5.85"))
        self.Button9.setProperty("CoordW", _translate("MainWindow", "-0.05"))
        self.Button10.setText(_translate("MainWindow", "10"))
        self.Button10.setProperty("CoordX", _translate("MainWindow", "10.16"))
        self.Button10.setProperty("CoordY", _translate("MainWindow", "-7.19"))
        self.Button10.setProperty("CoordW", _translate("MainWindow", "-0.15"))
        self.Button11.setText(_translate("MainWindow", "11"))
        self.Button11.setProperty("CoordX", _translate("MainWindow", "10.12"))
        self.Button11.setProperty("CoordY", _translate("MainWindow", "-8.46"))
        self.Button11.setProperty("CoordW", _translate("MainWindow", "-0.02"))
        self.Button12.setText(_translate("MainWindow", "12"))
        self.Button12.setProperty("CoordX", _translate("MainWindow", "10.024"))
        self.Button12.setProperty("CoordY", _translate("MainWindow", "-9.67"))
        self.Button12.setProperty("CoordW", _translate("MainWindow", "-0.016"))
        self.Button13.setText(_translate("MainWindow", "13"))
        self.Button13.setProperty("CoordX", _translate("MainWindow", "10.722"))
        self.Button13.setProperty("CoordY", _translate("MainWindow", "-9.63"))
        self.Button13.setProperty("CoordW", _translate("MainWindow", "0.9979"))
        self.Button14.setText(_translate("MainWindow", "14"))
        self.Button14.setProperty("CoordX", _translate("MainWindow", "10.945"))
        self.Button14.setProperty("CoordY", _translate("MainWindow", "-8.582"))
        self.Button14.setProperty("CoordW", _translate("MainWindow", "0.9979"))
        self.Button15.setText(_translate("MainWindow", "15"))
        self.Button15.setProperty("CoordX", _translate("MainWindow", "10.65"))
        self.Button15.setProperty("CoordY", _translate("MainWindow", "-7.13"))
        self.Button15.setProperty("CoordW", _translate("MainWindow", "0.9983"))
        self.Button16.setText(_translate("MainWindow", "16"))
        self.Button16.setProperty("CoordX", _translate("MainWindow", "10.787"))
        self.Button16.setProperty("CoordY", _translate("MainWindow", "-5.794"))
        self.Button16.setProperty("CoordW", _translate("MainWindow", "0.9955"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())