TebLocalPlannerROS:
  max_vel_x: 3
  min_vel_x: 3
  min_vel_theta: 3
  max_vel_theta: 2.0
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  min_obstacle_dist: 0.15
  inflation_dist: 0.2
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1


  footprint_model: 
    type: "polygon"
    vertices: [ [-0.1, -0.13], [-0.1, 0.13], [0.1, 0.13], [0.1, -0.13] ]

